name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node }}, ${{ matrix.os}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          CI: true
      - name: Run e2e tests (todo app)
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          install: false
          working-directory: packages/cevitxe-example-todo
          start: yarn start
          wait-on: 'http://localhost:3000'
        env:
          CI: true
